// content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-react-input-uuid-3/src/TextInput.jsx
// TextInput.jsx
import { useId } from "react";
import styles from "./TextInput.module.css";

export const TextInput = ({ label, type, id, error }) => {
	const uuid = useId();
	const realId = id || uuid;

	return (
		<>
			<label htmlFor={realId} className={styles.label}>
				{label}
			</label>
			<input
				id={realId}
				type={type}
				aria-invalid={!!error}
				aria-errormessage={realId + "-error"}
			/>
			<p className={styles.errormessage} id={realId + "-error"}>
				{error}
			</p>
		</>
	);
};

// content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/src/TextInput.vue
<!-- TextInput.vue -->
<script setup>
import { computed } from "vue";
import { v4 as uuidv4 } from "uuid";

const props = defineProps(["label", "type", "id", "error"]);

const uuid = uuidv4();

const realId = computed(() => props.id || uuid);
</script>

<template>
	<label :for="props.id" class="label">
		{{ props.label }}
	</label>
	<input
		:id="props.id"
		:type="props.type"
		:aria-invalid="!!props.error"
		:aria-errormessage="realId + '-error'"
	/>
	<p class="errormessage" :id="realId + '-error'">{{ props.error }}</p>
</template>

<style scoped>
.label {
	margin-right: 1rem;
}

.errormessage {
	color: red;
}
</style>
