// content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-angular-input-comp-3/src/TextInput.component.ts
import { Component, ChangeDetectionStrategy, input } from "@angular/core";

// TextInput.component.ts
@Component({
	selector: "text-input",
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<label [for]="id()" class="label">
			{{ label() }}
		</label>
		<input
			[id]="id()"
			[type]="type()"
			[attr.aria-invalid]="!!error()"
			[attr.aria-errormessage]="id() + '-error'"
		/>
		<p class="errormessage" [id]="id() + '-error'">{{ error() }}</p>
	`,
	styles: [
		`
			.label {
				margin-right: 1rem;
			}
			.errormessage {
				color: red;
			}
		`,
	],
})
export class TextInputComponent {
	label = input.required<string>();
	id = input.required<string>();
	type = input<string>();
	error = input<string>();
}

// content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/src/TextInput.vue
<!-- TextInput.vue -->
<script setup>
const props = defineProps(["label", "type", "id", "error"]);
</script>

<template>
	<label :for="props.id" class="label">
		{{ props.label }}
	</label>
	<input
		:id="props.id"
		:type="props.type"
		:aria-invalid="!!props.error"
		:aria-errormessage="props.id + '-error'"
	/>
	<p class="errormessage" :id="props.id + '-error'">{{ props.error }}</p>
</template>

<style scoped>
.label {
	margin-right: 1rem;
}

.errormessage {
	color: red;
}
</style>
