// content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-dependency-injection/ffg-fundamentals-angular-di-challenge-93/src/sidebar.component.ts
// sidebar.component.ts
import { Component, inject, Injectable } from "@angular/core";
import { ActionTypes } from "./context";

import { FileComponent } from "./file.component";

@Injectable()
class SidebarDirectories {
	actions = [] as any[];
}

function injectAndAssignActions(actions: any[]) {
	const sidebarDirectories = inject(ActionTypes);
	sidebarDirectories.actions = actions;
	return sidebarDirectories;
}

@Component({
	selector: "app-sidebar",
	imports: [FileComponent],
	providers: [
		{
			provide: ActionTypes,
			useClass: SidebarDirectories,
		},
	],
	template: `
		<div style="padding: 1rem">
			<h1 style="font-size: 1.25rem">Directories</h1>
			@for (directory of directories; track directory.id) {
				<file-item [name]="directory.name" [id]="directory.id" />
			}
		</div>
	`,
})
export class SidebarComponent {
	directories = [
		{
			name: "Movies",
			id: 1,
		},
		{
			name: "Documents",
			id: 2,
		},
		{
			name: "Etc",
			id: 3,
		},
	];

	getDirectoryById = (id: number) => {
		return this.directories.find((dir) => dir.id === id);
	};

	onCopy = (id: number) => {
		const dir = this.getDirectoryById(id)!;
		// Some browsers still do not support this
		if (navigator?.clipboard?.writeText) {
			navigator.clipboard.writeText(dir.name);
			alert("Name is copied");
		} else {
			alert("Unable to copy directory name due to browser incompatibility");
		}
	};

	sidebarDirectories = injectAndAssignActions([
		{
			label: "Copy directory name",
			fn: this.onCopy,
		},
	]);
}

// content/blog/ffg-fundamentals-dependency-injection/ffg-fundamentals-vue-di-challenge/src/Sidebar.vue
<!-- Sidebar.vue -->
<script setup>
import { provide } from "vue";
import File from "./File.vue";

const directories = [
  {
    name: "Movies",
    id: 1,
  },
  {
    name: "Documents",
    id: 2,
  },
  {
    name: "Etc",
    id: 3,
  },
];

const getDirectoryById = (id) => {
  return directories.find((dir) => dir.id === id);
};

const onCopy = (id) => {
  const dir = getDirectoryById(id);
  // Some browsers still do not support this
  if (navigator?.clipboard?.writeText) {
    navigator.clipboard.writeText(dir.name);
    alert("Name is copied");
  } else {
    alert("Unable to copy directory name due to browser incompatibility");
  }
};

provide("ContextMenu", {
  actions: [
    {
      label: "Copy directory name",
      fn: onCopy,
    },
  ],
});
</script>

<template>
  <div style="padding: 1rem">
    <h1 style="font-size: 1.25rem">Directories</h1>
    <File
      v-for="directory of directories"
      :key="directory.id"
      :name="directory.name"
      :id="directory.id"
    />
  </div>
</template>
