// content/blog/ffg-fundamentals-dependency-injection/ffg-fundamentals-vue-di-challenge-93/src/File.vue
<!-- File.vue -->
<script setup>
import { ref } from "vue";
import ContextMenu from "./ContextMenu.vue";

const props = defineProps(["name", "id"]);

const mouseBounds = ref({
	x: 0,
	y: 0,
});
const isOpen = ref(false);

const setIsOpen = (v) => (isOpen.value = v);

const contextMenu = ref();

function onContextMenu(e) {
	e.preventDefault();
	isOpen.value = true;
	mouseBounds.value = {
		x: e.clientX,
		y: e.clientY,
	};
	setTimeout(() => {
		contextMenu.value.focusMenu();
	}, 0);
}
</script>

<template>
	<button
		@contextmenu="onContextMenu($event)"
		style="display: block; width: 100%; margin-bottom: 1rem"
	>
		{{ props.name }}
	</button>
	<ContextMenu
		:data="props.id"
		ref="contextMenu"
		:isOpen="isOpen"
		@close="setIsOpen(false)"
		:x="mouseBounds.x"
		:y="mouseBounds.y"
	/>
</template>

// content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-dependency-injection/ffg-fundamentals-react-di-challenge-93/src/File.jsx
// File.jsx
import { useState, useRef, useEffect } from "react";
import { ContextMenu } from "./ContextMenu";

export const File = ({ name, id }) => {
	const [mouseBounds, setMouseBounds] = useState({
		x: 0,
		y: 0,
	});
	const [isOpen, setIsOpen] = useState(false);
	function onContextMenu(e) {
		e.preventDefault();
		setIsOpen(true);
		setMouseBounds({
			x: e.clientX,
			y: e.clientY,
		});
	}

	const contextMenuRef = useRef();

	useEffect(() => {
		if (isOpen) {
			setTimeout(() => {
				if (contextMenuRef.current) {
					contextMenuRef.current.focus();
				}
			}, 0);
		}
	}, [isOpen, mouseBounds]);

	return (
		<>
			<button
				onContextMenu={onContextMenu}
				style={{ display: "block", width: "100%", marginBottom: "1rem" }}
			>
				{name}
			</button>
			<ContextMenu
				data={id}
				ref={contextMenuRef}
				isOpen={isOpen}
				onClose={() => setIsOpen(false)}
				x={mouseBounds.x}
				y={mouseBounds.y}
			/>
		</>
	);
};
