// content/crutchcorn/collections/framework-field-guide-fundamentals-v1/posts/ffg-fundamentals-v1-dependency-injection/ffg-fundamentals-angular-di-challenge-93/src/context-menu.component.ts
// context-menu.component.ts
import {
	Component,
	ElementRef,
	EventEmitter,
	inject,
	Input,
	OnChanges,
	OnDestroy,
	OnInit,
	Output,
	SimpleChange,
	SimpleChanges,
	ViewChild,
} from "@angular/core";
import { LayoutComponent } from "./layout.component";
import { NgFor, NgIf } from "@angular/common";
import { ActionTypes } from "./context";

function injectAndGetActions() {
	const context = inject(ActionTypes);
	if (!context) return [];
	return context.actions;
}

@Component({
	selector: "context-menu",
	standalone: true,
	imports: [NgIf, NgFor],
	template: `
		<div
			*ngIf="isOpen && actions"
			#contextMenu
			tabIndex="0"
			[style]="
				'
          position: fixed;
          top: ' +
				y +
				'px;
          left: ' +
				x +
				'px;
          background: white;
          border: 1px solid black;
          border-radius: 16px;
          padding: 1rem;
        '
			"
		>
			<button (click)="close.emit(false)">X</button>
			<ul>
				<li *ngFor="let action of actions">
					<button (click)="action.fn(data); close.emit(false)">
						{{ action.label }}
					</button>
				</li>
			</ul>
		</div>
	`,
})
export class ContextMenuComponent implements OnInit, OnDestroy, OnChanges {
	@ViewChild("contextMenu", { static: false }) contextMenuRef!: ElementRef;
	@Input() isOpen!: boolean;
	@Input() x!: number;
	@Input() y!: number;
	@Input() data!: any;

	@Output() close = new EventEmitter<boolean>();

	actions = injectAndGetActions();

	closeIfOutside = (e: MouseEvent) => {
		const contextMenuEl = this.contextMenuRef?.nativeElement;
		if (!contextMenuEl) return;
		const isClickInside = contextMenuEl.contains(e.target);
		if (isClickInside) return;
		this.close.emit(false);
	};

	closeIfContextMenu = () => {
		if (!this.isOpen) return;
		this.close.emit(false);
	};

	previousListener: null | (() => void) = null;

	ngOnChanges(changes: SimpleChanges) {
		if (changes["isOpen"].previousValue !== changes["isOpen"].currentValue) {
			if (this.previousListener) {
				this.previousListener();
			}
			// Inside a timeout to make sure the initial context menu does not close the menu
			setTimeout(() => {
				document.addEventListener("contextmenu", this.closeIfContextMenu);
			}, 0);

			this.previousListener = () =>
				document.removeEventListener("contextmenu", this.closeIfContextMenu);
		}
	}

	ngOnInit() {
		document.addEventListener("click", this.closeIfOutside);
	}

	ngOnDestroy() {
		document.removeEventListener("click", this.closeIfOutside);
	}

	focusMenu() {
		this.contextMenuRef.nativeElement.focus();
	}
}

// content/blog/ffg-fundamentals-dependency-injection/ffg-fundamentals-vue-di-challenge-93/src/ContextMenu.vue
<!-- ContextMenu.vue -->
<script setup>
import { ref, onMounted, onUnmounted, inject, computed, watch } from "vue";

const props = defineProps(["isOpen", "x", "y", "data"]);

const emit = defineEmits(["close"]);

const context = inject("ContextMenu");

const actions = computed(() => {
	if (!context) return [];
	return context.actions;
});

const contextMenuRef = ref(null);

function closeIfOutside(e) {
	const contextMenuEl = contextMenuRef.value;
	if (!contextMenuEl) return;
	const isClickInside = contextMenuEl.contains(e.target);
	if (isClickInside) return;
	emit("close");
}

const closeIfContextMenu = () => {
	if (!props.isOpen) return;
	emit("close");
};

// This must live in a watch, as `onMounted` will run whether the `isOpen` boolean is set or not
watch(
	() => props.isOpen,
	(_, __, onCleanup) => {
		// Inside a timeout to make sure the initial context menu does not close the menu
		setTimeout(() => {
			document.addEventListener("contextmenu", closeIfContextMenu);
		}, 0);

		onCleanup(() =>
			document.removeEventListener("contextmenu", closeIfContextMenu),
		);
	},
);

onMounted(() => {
	document.addEventListener("click", closeIfOutside);
});

onUnmounted(() => {
	document.removeEventListener("click", closeIfOutside);
});

function focusMenu() {
	contextMenuRef.value.focus();
}

defineExpose({
	focusMenu,
});
</script>

<template>
	<div
		v-if="props.isOpen && context"
		ref="contextMenuRef"
		tabIndex="0"
		:style="`
          position: fixed;
          top: ${props.y}px;
          left: ${props.x}px;
          background: white;
          border: 1px solid black;
          border-radius: 16px;
          padding: 1rem;
        `"
	>
		<button @click="emit('close')">X</button>
		<ul>
			<li v-for="action of actions">
				<button
					@click="
						action.fn(data);
						emit('close', false);
					"
				>
					{{ action.label }}
				</button>
			</li>
		</ul>
	</div>
</template>
