// content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-element-reference/ffg-fundamentals-react-real-world-usage-64/src/main.jsx
import { createRoot } from "react-dom/client";
import { useState, useEffect } from "react";

function App() {
	const [mouseBounds, setMouseBounds] = useState({
		x: 0,
		y: 0,
	});

	const [isOpen, setIsOpen] = useState(false);

	function onContextMenu(e) {
		e.preventDefault();
		setIsOpen(true);
		setMouseBounds({
			x: e.clientX,
			y: e.clientY,
		});
	}

	const [contextMenu, setContextMenu] = useState();

	useEffect(() => {
		if (contextMenu) {
			contextMenu.focus();
		}
	}, [contextMenu]);

	useEffect(() => {
		if (!contextMenu) return;
		const closeIfOutsideOfContext = (e) => {
			const isClickInside = contextMenu.contains(e.target);
			if (isClickInside) return;
			setIsOpen(false);
		};
		document.addEventListener("click", closeIfOutsideOfContext);
		return () => document.removeEventListener("click", closeIfOutsideOfContext);
	}, [contextMenu]);

	return (
		<>
			<div style={{ marginTop: "5rem", marginLeft: "5rem" }}>
				<div onContextMenu={onContextMenu}>Right click on me!</div>
			</div>
			{isOpen && (
				<div
					ref={(el) => setContextMenu(el)}
					tabIndex={0}
					style={{
						position: "fixed",
						top: mouseBounds.y,
						left: mouseBounds.x,
						background: "white",
						border: "1px solid black",
						borderRadius: 16,
						padding: "1rem",
					}}
				>
					<button onClick={() => setIsOpen(false)}>X</button>
					This is a context menu
				</div>
			)}
		</>
	);
}

createRoot(document.getElementById("root")).render(<App />);

// content/crutchcorn/collections/framework-field-guide-fundamentals-v1/posts/ffg-fundamentals-v1-component-reference/ffg-fundamentals-angular-focused-comp-ref-68/src/main.ts
import "zone.js";
import { bootstrapApplication } from "@angular/platform-browser";

import {
	AfterViewInit,
	Component,
	ElementRef,
	EventEmitter,
	Input,
	OnDestroy,
	Output,
	QueryList,
	ViewChild,
	ViewChildren,
} from "@angular/core";
import { NgIf } from "@angular/common";

@Component({
	selector: "context-menu",
	standalone: true,
	imports: [NgIf],
	template: `
		<div
			*ngIf="isOpen"
			tabIndex="0"
			#contextMenu
			[style]="
				'
        position: fixed;
        top: ' +
				y +
				'px;
        left: ' +
				x +
				'px;
        background: white;
        border: 1px solid black;
        border-radius: 16px;
        padding: 1rem;
      '
			"
		>
			<button (click)="close.emit()">X</button>
			This is a context menu
		</div>
	`,
})
class ContextMenuComponent implements AfterViewInit, OnDestroy {
	@ViewChild("contextMenu") contextMenu!: ElementRef<HTMLElement>;

	@Input() isOpen!: boolean;
	@Input() x!: number;
	@Input() y!: number;

	@Output() close = new EventEmitter();

	focus() {
		this.contextMenu?.nativeElement?.focus();
	}

	closeIfOutsideOfContext = (e: MouseEvent) => {
		const contextMenuEl = this.contextMenu?.nativeElement;
		if (!contextMenuEl) return;
		const isClickInside = contextMenuEl.contains(e.target as HTMLElement);
		if (isClickInside) return;
		this.close.emit();
	};

	ngAfterViewInit() {
		document.addEventListener("click", this.closeIfOutsideOfContext);
	}

	ngOnDestroy() {
		document.removeEventListener("click", this.closeIfOutsideOfContext);
	}
}

@Component({
	selector: "app-root",
	standalone: true,
	imports: [NgIf, ContextMenuComponent],
	template: `
		<div style="margin-top: 5rem; margin-left: 5rem">
			<div #contextOrigin (contextmenu)="open($event)">Right click on me!</div>
		</div>
		<context-menu
			#contextMenu
			(close)="close()"
			[isOpen]="isOpen"
			[x]="mouseBounds.x"
			[y]="mouseBounds.y"
		/>
	`,
})
class AppComponent {
	@ViewChild("contextMenu") contextMenu!: ContextMenuComponent;

	isOpen = false;

	mouseBounds = {
		x: 0,
		y: 0,
	};

	close() {
		this.isOpen = false;
	}

	open(e: MouseEvent) {
		e.preventDefault();
		this.isOpen = true;
		this.mouseBounds = {
			x: e.clientX,
			y: e.clientY,
		};
		setTimeout(() => {
			this.contextMenu.focus();
		}, 0);
	}
}

bootstrapApplication(AppComponent);
