// content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-dependency-injection/ffg-fundamentals-angular-di-challenge-93/src/layout.component.ts
// layout.component.ts
import { Component } from "@angular/core";

@Component({
	selector: "app-layout",
	template: `
		<div style="display: flex; flex-wrap: nowrap; min-height: 100vh ">
			<div
				style="
              width: 150px;
              background-color: lightgray;
              border-right: 1px solid gray;
            "
			>
				<ng-content select="[sidebar]" />
			</div>
			<div style="width: 1px; flex-grow: 1">
				<ng-content />
			</div>
		</div>
	`,
})
export class LayoutComponent {}

// content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-component-reference/ffg-fundamentals-vue-comp-ref-challenge-69/src/Layout.vue
<!-- Layout.vue -->
<script setup>
const props = defineProps(["sidebarWidth"]);
</script>

<template>
	<div style="display: flex; flex-wrap: nowrap; min-height: 100vh">
		<div
			:style="`
          width: ${props.sidebarWidth}px;
          height: 100vh;
          overflow-y: scroll;
          border-right: 2px solid #bfbfbf;
        `"
		>
			<slot name="sidebar" />
		</div>
		<div style="width: 1px; flex-grow: 1">
			<slot />
		</div>
	</div>
</template>
