// content/blog/ffg-fundamentals-dependency-injection/ffg-fundamentals-vue-di-challenge-93/src/File.vue
<!-- File.vue -->
<script setup>
import { ref } from "vue";
import ContextMenu from "./ContextMenu.vue";

const props = defineProps(["name", "id"]);

const mouseBounds = ref({
	x: 0,
	y: 0,
});
const isOpen = ref(false);

const setIsOpen = (v) => (isOpen.value = v);

const contextMenu = ref();

function onContextMenu(e) {
	e.preventDefault();
	isOpen.value = true;
	mouseBounds.value = {
		x: e.clientX,
		y: e.clientY,
	};
	setTimeout(() => {
		contextMenu.value.focusMenu();
	}, 0);
}
</script>

<template>
	<button
		@contextmenu="onContextMenu($event)"
		style="display: block; width: 100%; margin-bottom: 1rem"
	>
		{{ props.name }}
	</button>
	<ContextMenu
		:data="props.id"
		ref="contextMenu"
		:isOpen="isOpen"
		@close="setIsOpen(false)"
		:x="mouseBounds.x"
		:y="mouseBounds.y"
	/>
</template>

// content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-dependency-injection/ffg-fundamentals-angular-di-challenge-93/src/file.component.ts
// file.component.ts
import {
	Component,
	input,
	Input,
	signal,
	viewChild,
	ViewChild,
} from "@angular/core";
import { ContextMenuComponent } from "./context-menu.component";

@Component({
	selector: "file-item",
	imports: [ContextMenuComponent],
	template: `
		<button
			(contextmenu)="onContextMenu($event)"
			style="display: block; width: 100%; margin-bottom: 1rem"
		>
			{{ name() }}
		</button>
		<context-menu
			#contextMenu
			[data]="id()"
			[isOpen]="isOpen()"
			(close)="setIsOpen(false)"
			[x]="mouseBounds().x"
			[y]="mouseBounds().y"
		/>
	`,
})
export class FileComponent {
	contextMenu = viewChild.required("contextMenu", {
		read: ContextMenuComponent,
	});
	name = input.required<string>();
	id = input.required<number>();

	mouseBounds = signal({
		x: 0,
		y: 0,
	});

	isOpen = signal(false);

	setIsOpen = (v: boolean) => this.isOpen.set(v);

	onContextMenu(e: MouseEvent) {
		e.preventDefault();
		this.isOpen.set(true);
		this.mouseBounds.set({
			x: e.clientX,
			y: e.clientY,
		});
		setTimeout(() => {
			this.contextMenu().focusMenu();
		}, 0);
	}
}
