// content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-dependency-injection/ffg-fundamentals-react-di-challenge-93/src/FileList.jsx
import { useState } from "react";
import { ContextMenuContext } from "./ContextMenuContext";
import { File } from "./File";

export const FileList = () => {
	const [files, setFiles] = useState([
		{
			name: "Testing.wav",
			id: 1,
		},
		{
			name: "Secrets.txt",
			id: 2,
		},
		{
			name: "Other.md",
			id: 3,
		},
	]);

	const getFileIndexById = (id) => {
		return files.findIndex((file) => file.id === id);
	};

	const onRename = (id) => {
		const fileIndex = getFileIndexById(id);
		const file = files[fileIndex];
		const newName = prompt(
			`What do you want to rename the file ${file.name} to?`,
		);
		if (!newName) return;
		setFiles((v) => {
			const newV = [...v];
			newV[fileIndex] = {
				...file,
				name: newName,
			};
			return newV;
		});
	};

	const onDelete = (id) => {
		const fileIndex = getFileIndexById(id);
		setFiles((v) => {
			const newV = [...v];
			newV.splice(fileIndex, 1);
			return newV;
		});
	};

	return (
		<ContextMenuContext.Provider
			value={{
				actions: [
					{
						label: "Rename",
						fn: onRename,
					},
					{
						label: "Delete",
						fn: onDelete,
					},
				],
			}}
		>
			<div style={{ padding: "1rem" }}>
				<h1>Files</h1>
				{files.map((file) => {
					return <File key={file.id} name={file.name} id={file.id} />;
				})}
			</div>
		</ContextMenuContext.Provider>
	);
};

// content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-dependency-injection/ffg-fundamentals-angular-di-challenge-93/src/file-list.component.ts
// file-list.component.ts
import { Component, inject, Injectable } from "@angular/core";
import { ActionTypes } from "./context";

import { FileComponent } from "./file.component";

@Injectable()
class FileListActions {
	actions = [] as any[];
}

function injectAndAssignActions(actions: any[]) {
	const sidebarDirectories = inject(ActionTypes);
	sidebarDirectories.actions = actions;
	return sidebarDirectories;
}

@Component({
	selector: "file-list",
	standalone: true,
	imports: [FileComponent],
	providers: [
		{
			provide: ActionTypes,
			useClass: FileListActions,
		},
	],
	template: `
		<div style="padding: 1rem">
		  <h1>Files</h1>
		  @for (file of files; track file.id) {
		    <file-item [name]="file.name" [id]="file.id" />
		  }
		</div>
		`,
})
export class FileListComponent {
	files = [
		{
			name: "Testing.wav",
			id: 1,
		},
		{
			name: "Secrets.txt",
			id: 2,
		},
		{
			name: "Other.md",
			id: 3,
		},
	];

	getFileIndexById = (id: number) => {
		return this.files.findIndex((file) => file.id === id);
	};

	onRename = (id: number) => {
		const fileIndex = this.getFileIndexById(id)!;
		const file = this.files[fileIndex];
		const newName = prompt(
			`What do you want to rename the file ${file.name} to?`,
		);
		if (!newName) return;
		this.files[fileIndex] = {
			...file,
			name: newName,
		};
	};

	onDelete = (id: number) => {
		const fileIndex = this.getFileIndexById(id);
		this.files.splice(fileIndex, 1);
	};

	fileListActions = injectAndAssignActions([
		{
			label: "Rename",
			fn: this.onRename,
		},
		{
			label: "Delete",
			fn: this.onDelete,
		},
	]);
}
