// content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-element-reference/ffg-fundamentals-angular-real-world-usage-64/src/main.ts
import "zone.js";
import { bootstrapApplication } from "@angular/platform-browser";

import {
	Component,
	ElementRef,
	viewChild,
	signal,
	afterRenderEffect,
} from "@angular/core";

@Component({
	selector: "app-root",
	template: `
		<div style="margin-top: 5rem; margin-left: 5rem">
			<div (contextmenu)="open($event)">Right click on me!</div>
		</div>
		@if (isOpen()) {
			<div
				tabIndex="0"
				#contextMenu
				[style]="
					'
		position: fixed;
		top: ' +
					mouseBounds().y +
					'px;
		left: ' +
					mouseBounds().x +
					'px;
		background: white;
		border: 1px solid black;
		border-radius: 16px;
		padding: 1rem;
		'
				"
			>
				<button (click)="close()">X</button>
				This is a context menu
			</div>
		}
	`,
})
class AppComponent {
	contextMenu = viewChild("contextMenu", { read: ElementRef<HTMLElement> });

	isOpen = signal(false);

	mouseBounds = signal({
		x: 0,
		y: 0,
	});

	closeIfOutsideOfContext = (e: MouseEvent) => {
		const contextMenuEl = this.contextMenu()?.nativeElement;
		if (!contextMenuEl) return;
		const isClickInside = contextMenuEl.contains(e.target as HTMLElement);
		if (isClickInside) return;
		this.isOpen.set(false);
	};

	constructor() {
		afterRenderEffect((onCleanup) => {
			document.addEventListener("click", this.closeIfOutsideOfContext);
			onCleanup(() => {
				document.removeEventListener("click", this.closeIfOutsideOfContext);
			});
		});
	}

	close() {
		this.isOpen.set(false);
	}

	open(e: MouseEvent) {
		e.preventDefault();
		this.isOpen.set(true);
		this.mouseBounds.set({
			x: e.clientX,
			y: e.clientY,
		});
		// Wait until the element is rendered before focusing it
		setTimeout(() => {
			this.contextMenu()?.nativeElement.focus();
		}, 0);
	}
}

bootstrapApplication(AppComponent);

// content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-element-reference/ffg-fundamentals-react-real-world-usage-64/src/main.jsx
import { createRoot } from "react-dom/client";
import { useState, useEffect } from "react";

function App() {
	const [mouseBounds, setMouseBounds] = useState({
		x: 0,
		y: 0,
	});

	const [isOpen, setIsOpen] = useState(false);

	function onContextMenu(e) {
		e.preventDefault();
		setIsOpen(true);
		setMouseBounds({
			x: e.clientX,
			y: e.clientY,
		});
	}

	const [contextMenu, setContextMenu] = useState();

	useEffect(() => {
		if (contextMenu) {
			contextMenu.focus();
		}
	}, [contextMenu]);

	useEffect(() => {
		if (!contextMenu) return;
		const closeIfOutsideOfContext = (e) => {
			const isClickInside = contextMenu.contains(e.target);
			if (isClickInside) return;
			setIsOpen(false);
		};
		document.addEventListener("click", closeIfOutsideOfContext);
		return () => document.removeEventListener("click", closeIfOutsideOfContext);
	}, [contextMenu]);

	return (
		<>
			<div style={{ marginTop: "5rem", marginLeft: "5rem" }}>
				<div onContextMenu={onContextMenu}>Right click on me!</div>
			</div>
			{isOpen && (
				<div
					ref={(el) => setContextMenu(el)}
					tabIndex={0}
					style={{
						position: "fixed",
						top: mouseBounds.y,
						left: mouseBounds.x,
						background: "white",
						border: "1px solid black",
						borderRadius: 16,
						padding: "1rem",
					}}
				>
					<button onClick={() => setIsOpen(false)}>X</button>
					This is a context menu
				</div>
			)}
		</>
	);
}

createRoot(document.getElementById("root")).render(<App />);
